version: '3.8'

services:
  joplin:
    image: jspiers/headless-joplin:2.13.2-node-20.11.1
    expose:
      - 80
    volumes:
      - joplin-data:/home/node/.config/joplin
    secrets:
      - joplin-config.json
    networks:
      - joplin
    # Override healthcheck interval until start-interval is implemented (in moby v25)
    healthcheck:
      interval: 5s
    restart: no # for debugging

  imap:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20-bookworm
    environment:
      JOPLIN_IMAP_DEBUG: "true"
      JOPLIN_URL: http://joplin
      JOPLIN_TOKEN: ${JOPLIN_TOKEN:-mytoken}
      JOPLIN_NOTEBOOK: ${COMPOSE_PROJECT_NAME?}
      IMAP_SERVER: ${IMAP_SERVER?}
      IMAP_USERNAME: ${IMAP_USERNAME?}
      IMAP_PASSWORD: ${IMAP_PASSWORD?}
      IMAP_MAILBOX: ${IMAP_MAILBOX:-INBOX}
      IMAP_MAX_POLL_INTERVAL_SECONDS: ${IMAP_MAX_POLL_INTERVAL_SECONDS:-300}
    depends_on:
      joplin:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - joplin
      - public

volumes:
  joplin-data: {}

secrets:
  joplin-config.json:
    file: ./joplin-config.json

networks:
  joplin:
    internal: true
  public: {}

