version: '3.8'

services:
  joplin:
    image: jspiers/headless-joplin:2.12.1-node-18.18.0
    expose:
      - 80
    volumes:
      - joplin-data:/home/node/.config/joplin
      # - sync:/sync
    secrets:
      - joplin-config.json
    networks:
      - joplin
    # override healthcheck interval until start-interval is implemented (in moby v25)
    healthcheck:
      interval: 5s
    restart: no # for debugging

  # Check out the joplin-utils git repo and run joplin-api tests
  # against the API port of the 'joplin' container
  utils:
    build:
      additional_contexts:
        # github: https://github.com/rxliuli/joplin-utils.git#master
        github: https://github.com/rxliuli/joplin-utils.git#9a052287088217715b00c87212005732b0bee2e9
      dockerfile_inline: |
        FROM node:20-bookworm
        RUN apt update -y && apt install -y --no-install-recommends \
          neovim \
          direnv
        RUN npm install -g pnpm
        RUN mkdir -p /work/joplin-utils
        WORKDIR /work/joplin-utils
        COPY --from=github . .
        RUN pnpm i
        RUN pnpm pnpm setup-all
    environment:
      JOPLIN_TOKEN: ${JOPLIN_TOKEN:-mytoken}
      JOPLIN_URL: http://joplin
    # Create .env.local file expected by "pnpm test" command, then run it
    command:
      - bash
      - -ec
      - |
        cat << EOF > .env.local
        URL=$${JOPLIN_URL}
        TOKEN=$${JOPLIN_TOKEN}
        EOF
        while true
        do
          pnpm test
          sleep 60
        done
    working_dir: /work/joplin-utils/packages/joplin-api
    volumes:
      - /home/jeff/.bashrc:/root/.bashrc:ro
    networks:
      - joplin
      - public
    depends_on:
      joplin:
        condition: service_healthy
    restart: no # for debugging

  imap:
    profiles:
      - imap
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20-bookworm
    environment:
      JOPLIN_IMAP_DEBUG: "true"
      JOPLIN_URL: http://joplin
      JOPLIN_TOKEN: ${JOPLIN_TOKEN:-mytoken}
      JOPLIN_NOTEBOOK: ${COMPOSE_PROJECT_NAME?}
      IMAP_SERVER: ${IMAP_SERVER?}
      IMAP_USERNAME: ${IMAP_USERNAME?}
      IMAP_PASSWORD: ${IMAP_PASSWORD?}
      IMAP_MAILBOX: ${IMAP_MAILBOX:-INBOX}
      IMAP_MAX_POLL_INTERVAL_SECONDS: ${IMAP_MAX_POLL_INTERVAL_SECONDS:-300}
    depends_on:
      joplin:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - joplin
      - public

volumes:
  joplin-data: {}
  # sync: {}

secrets:
  joplin-config.json:
    file: ./joplin-config.json

networks:
  joplin:
    internal: true
  public: {}
